-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 14:10:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data_players
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data_players
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_players` DEFAULT CHARACTER SET utf8 ;
USE `data_players` ;

-- -----------------------------------------------------
-- Table `data_players`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_players`.`pais` (
  `cod_pais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_pais`),
  UNIQUE INDEX `cod_pais_UNIQUE` (`cod_pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_players`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_players`.`jogo` (
  `cod_jogo` INT NOT NULL AUTO_INCREMENT,
  `nome_jogo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_jogo`),
  UNIQUE INDEX `cod_jogo_UNIQUE` (`cod_jogo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_players`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_players`.`jogador` (
  `cod_jogador` INT NOT NULL AUTO_INCREMENT,
  `nome_jogador` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `num_vitorias` INT NOT NULL,
  `num_derrotas` INT NOT NULL,
  `total_partidas` INT NOT NULL,
  `cod_pais` INT NOT NULL,
  `cod_jogo` INT NOT NULL,
  PRIMARY KEY (`cod_jogador`),
  UNIQUE INDEX `cod_jogador_UNIQUE` (`cod_jogador` ASC) VISIBLE,
  INDEX `fk_jogador_pais_idx` (`cod_pais` ASC) VISIBLE,
  INDEX `fk_jogador_jogo1_idx` (`cod_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_jogador_pais`
    FOREIGN KEY (`cod_pais`)
    REFERENCES `data_players`.`pais` (`cod_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogador_jogo1`
    FOREIGN KEY (`cod_jogo`)
    REFERENCES `data_players`.`jogo` (`cod_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
